Find the Difference - Easy

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

class Solution {
public:
    char findTheDifference(string s, string t) {
        int se[200] = {0};
        for(int i=0;i<s.length();i++){
            se[s[i]]++;
        }
        for(int i=0;i<t.length();i++){
            se[t[i]]--;
            if(se[t[i]]<0) return t[i];
        }
        return 0;
    }
};